import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import styles2 from "@/styles/Login.module.scss";
import { useDice } from "@/hooks/useDice.js";

const inter = Inter({ subsets: ["latin"] });

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles2.airDesktopContainer}>
        <div className={styles2.container}>
          <h1>Login</h1>
          <form>
            <label for="username">Username</label>
            <input type="text" id="username" name="username" required />

            <label for="password">Password</label>
            <input type="password" id="password" name="password" required />

            <button type="submit">Login</button>

            <div className={styles2.googleLogin}>
              <a href="#">
                <Image
                  src="/g-logo.png"
                  width={100}
                  height={24}
                  priority
                />
                Login with Google
              </a>
            </div>
          </form>
        </div>
      </main>
    </>
  );
}
