import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import styles2 from "@/styles/PlayerSheet.module.scss";
import { useDice } from "@/hooks/useDice.js";

const inter = Inter({ subsets: ["latin"] });

export default function PlayerSheet() {
  const { setDice, setNumberOfThrows, diceThrow, diceResult } = useDice();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          
          <div>
            <input
              type="number"
              onChange={() => setDice(event.target.value)}
            ></input>
            <input
              type="number"
              onChange={() => setNumberOfThrows(event.target.value)}
            ></input>
            <button onClick={() => diceThrow()}>calcula tu tirada</button>
            <p>{diceResult}</p>
          </div>

        </div>

        <div className={styles2.container}>

        </div>

        
      </main>
    </>
  );
}
